### PR TITLE
Speaker starter kit intial materials

### PR DESCRIPTION
**Pull request by gadenbuie**
This PR adds speaker guidelines with a speaker checklist, resources, tips, and more, in addition to a talk README template and a starter R companion script.

My hope is that this streamlines a lot of the process in terms of prepping for a talk and updating our online materials, while establishing a consistent starting point for our speakers.

Your feedback is welcomed -- especially @thomas-keller as our next presenter!

It's probably easier to review if you look at the [repo at this branch](https://github.com/TampaUseRs/speaker-starter-kit/tree/draft-materials).

### CODE REVIEW

**Review by thomas-keller — COMMENTED** [review]
I think this is quite good. You might consider adding a link to the software carpentries section on live coding  https://carpentries.github.io/instructor-training/15-live/

It reiterates several of the points you've already made.

They have a have nice good/bad live coding comparison on that webpage., each about 1.5 minutes long.

The only other comment I have is that it might be useful to be more explicit about default font sizes, since a lot of people tend to use Rmarkdown/xaringan . 130%? 40p fontsize?

**Comment by gadenbuie** [comment]
Thanks @thomas-keller, the software carpentries section on live coding definitely changed my opinion on live coding, so I agree a link would be good there. 

For font sizes my plan is to add starter slides in several formats and set the default there. But totally agree, 130% the default is a great starting point.

Thanks for your notes and let me know if you notice anything else as you go through the process!

**Comment by tgerke** [comment]
I agree with @thomas-keller, this is really awesome. 

My only suggestion might be to position the R markdown slide preparation as recommended; as it stands it may look required (by contrast, git usage nicely reads a clearly optional but preferred). I agree that it would be good for consistency across the presentations, but I don't want to put off any would-be presenters that are more at the beginner end of the spectrum. Looking forward, I think we could grow in that space, and it would likely benefit us to keep it in mind for current practice.

**Comment by gadenbuie** [comment]
Thanks @tgerke, I agree, I meant it to be recommended but I think that when I added headers it promoted it to closer to required, so I'll add some text under the Slides section as a way of introduction.

I also want to include some posts on general slide making and presenting, along the lines of
- [The Art of Slide Design](https://speakerdeck.com/mseckington/the-art-of-slide-design)
- [Presenting Effectively](https://kieranhealy.org/blog/archives/2018/03/24/making-slides/)
- [7 Tips for Presenting Bulleted Lists in Digital Content](https://www.nngroup.com/articles/presenting-bulleted-lists/)

Any other recommendations?

**Comment by thomas-keller** [comment]
You may have seen this, but some extra materials from Jenny Bryan's R-user [slide guide](https://www.tidyverse.org/articles/2018/07/carpe-talk/) 

* [how to give a talk](http://www.howtogiveatalk.com/) (I hadn't seen this before but I rather like it just from the 5 seconds of looking at it)
* [marketing for data science](https://medium.com/indeed-data-science/marketing-for-data-science-a-7-step-go-to-market-plan-for-your-next-data-product-60c034c34d55)

**Comment by gadenbuie** [comment]
@thomas-keller thanks for sharing! I have that post ear-marked for inclusion here. The [GitHub Issue Thread](https://github.com/tidyverse/tidyverse.org/issues/182) has a lot of great examples as well 😄

**Comment by thomas-keller** [comment]
What is the best way to contact @tgerke / @jhcreed to give the talk title info? There's no private messaging in github, so please provide either a tampa-Rusers throwaway email if you have one, or a public-facing email you are comfortable sharing.

I'm probably overthinking this; how have people done this in the past?

**Comment by jhcreed** [comment]
@thomas-keller  you can email us at Jordan.H.Creed@moffitt.org and Travis.Gerke@moffitt.org. I had emailed you a few weeks ago to the gmail account you had previously given me.

**Comment by gadenbuie** [comment]
Thanks @tgerke and @thomas-keller for the feedback. I just pushed [a few updates](
https://github.com/TampaUseRs/speaker-starter-kit/pull/2/commits/76aeda46c0a775559691461dbc85936b06e39cda) that

- Put presentation tips before Rmd tips
- Advocate slightly less strongly for Rmd slides
- Add links to presentation tips
- Add link to live coding tips
- Recommend contacting via Meetup/Twitter
- Added many links to TRUG website/twitter/meetup

I took out the contact @jhcreed or @tgerke references and replaced them with "contact via Meetup/Twitter" for future-proofing.

**Comment by gadenbuie** [comment]
Based on @jhcreed's suggestion, I added timeline requirements to the checklist, i.e. 3 weeks before..., 2 weeks before..., 1-3 days before...

I think this is ready to go. @tgerke @jhcreed or @Kris-Kindle can you take a quick look and [give a review](https://help.github.com/articles/about-pull-request-reviews/)?

**Review by Kris-Kindle — APPROVED** [review]
Looks good to me. Lots of good setup material for future speakers.

**Pull request merged**
